/* The daily brief view (סיכום יומי) — one day at a time, arena by arena.

   Data arrives via brief.js (const BRIEF, generated by scripts\brief_build.py):
   BRIEF.days, newest first, one record per day carrying the Hebrew narrative
   and the extras per arena — the statements, the strikes against the Houthis
   and the world reaction, all of which are TEXT with a source and can never
   become board events (see BRIEF.md).

   The EVENT LIST under each arena is deliberately NOT stored in the brief: it
   is derived here from DATA.attacks by (date, front), so a record recovered
   late for an old day always shows the board's current truth. brief_build.py
   fails the build when a stored day's counts disagree with the records, which
   is what keeps the narrative and this derivation from drifting on a published
   board.

   Reads app.js globals (itemHtml, esc, ltr, fmtDate, frontHe) and filters.js's
   FRONTS at call time — loaded after both. No ES modules (file://). */
"use strict";

(function () {
  const pane = document.getElementById("daily-pane");
  if (!pane) return;

  /* Extras appear grouped, in this order, under these labels. Same words the
     rubric uses; an unknown kind falls into none of the groups and is dropped
     by the renderer rather than mislabelled. */
  const EXTRA_GROUPS = [
    { kind: "statement",      he: "הצהרות ואיומים" },
    { kind: "counter_attack", he: "תקיפות נגד החות'ים" },
    { kind: "world",          he: "תגובות בעולם" },
  ];

  let mode = "day";   /* "day" | "week" — the switch shows only when weeks exist */
  let dayIndex = 0;   /* into BRIEF.days, 0 = newest */
  let weekIndex = 0;  /* into BRIEF.weeks, 0 = newest */

  /* Hebrew agrees with the number and has a dual — never a bare count glued to
     the noun (lessons ledger, 2026-08-02). Zero returns "" because the quiet
     arena says its own line and a "0 אירועים" chip would read as a measurement. */
  function countHe(n) {
    if (!n) return "";
    if (n === 1) return "אירוע אחד";
    if (n === 2) return "שני אירועים";
    return ltr(n) + " אירועים";
  }

  function weekdayHe(iso) {
    const [y, m, d] = String(iso).split("-").map(Number);
    return new Intl.DateTimeFormat("he-IL", { weekday: "long" })
      .format(new Date(y, m - 1, d));
  }

  function eventsOf(date, front) {
    if (typeof DATA === "undefined") return [];
    return DATA.attacks.filter((r) => r.date === date && r.front === front);
  }

  function weekEventsOf(from, to, front) {
    if (typeof DATA === "undefined") return [];
    return DATA.attacks.filter(
      (r) => r.date >= from && r.date <= to && r.front === front);
  }

  /* The displayed range of a week. Keyed by its true Tuesday, but the stub
     first week only COVERS from the window's opening day — the shown range
     is the covered one (12.7–13.7), never the claimed Tuesday. The oldest
     daily IS the window start: brief_build enforces contiguity from it. */
  function weekRange(week) {
    const oldest = BRIEF.days[BRIEF.days.length - 1].date;
    const [y, m, d] = week.week_start.split("-").map(Number);
    const end = new Date(y, m - 1, d + 6);
    const pad = (n) => String(n).padStart(2, "0");
    return {
      from: week.week_start > oldest ? week.week_start : oldest,
      to: end.getFullYear() + "-" + pad(end.getMonth() + 1) + "-" +
        pad(end.getDate()),
    };
  }

  function badgeHtml(front) {
    return front.color
      ? '<span class="badge" style="--chip-c: var(--f-' + front.key +
        "); --chip-t: var(--f-" + front.key + '-tint)">' + esc(front.he) +
        "</span>"
      : '<span class="kbadge">' + esc(front.he) + "</span>";
  }

  /* The day/week switch — rendered only once weekly records exist; a
     control that opens an empty view is a broken promise. */
  function switchHtml() {
    if (!(BRIEF.weeks || []).length) return "";
    const btn = (key, label) =>
      '<button type="button" class="mode-btn" data-mode="' + key +
      '" aria-pressed="' + (mode === key) + '">' + label + "</button>";
    return '<div class="mode-switch" aria-label="תקופת הסיכום">' +
      btn("day", "יומי") + btn("week", "שבועי") + "</div>";
  }

  function wireSwitch() {
    pane.querySelectorAll(".mode-btn").forEach((btn) => {
      btn.addEventListener("click", () => {
        if (btn.dataset.mode === mode) return;
        mode = btn.dataset.mode;
        render();
        window.scrollTo(0, 0);
      });
    });
  }

  function extrasHtml(arena) {
    const extras = (arena && arena.extras) || [];
    if (!extras.length) return "";
    return EXTRA_GROUPS.map((group) => {
      const rows = extras.filter((x) => x.kind === group.kind);
      if (!rows.length) return "";
      return '<div class="x-group"><h4 class="x-label">' + esc(group.he) + "</h4>" +
        rows.map((x) =>
          '<div class="x-row"><p class="x-text">' + esc(x.text_he) +
          '<span class="x-src">— ' +
          (x.url
            ? '<a href="' + esc(x.url) + '" target="_blank" rel="noopener">' +
              esc(x.source_he) + "</a>"
            : esc(x.source_he)) +
          "</span></p></div>").join("") +
        "</div>";
    }).join("");
  }

  /* The development types, tagged inline the way Ziv asked for them by
     example — "say, this is a strategic development, this is a military
     development" (2026-09-01). An unknown kind renders untagged rather
     than mislabelled. */
  const DEVEL_HE = {
    strategic: "התפתחות אסטרטגית",
    military: "התפתחות צבאית",
    political: "התפתחות מדינית",
    economic: "התפתחות כלכלית",
    humanitarian: "התפתחות הומניטרית",
  };

  function develHtml(arena) {
    const items = arena.devel || [];
    if (!items.length) return "";
    return items.map((d) =>
      '<div class="dv-row"><p class="dv-text">' +
      (DEVEL_HE[d.kind]
        ? '<strong class="dv-tag">' + esc(DEVEL_HE[d.kind]) + ":</strong> "
        : "") +
      esc(d.text_he) + "</p></div>").join("");
  }

  /* One arena section, in Ziv's order: developments first, extras next,
     attacks LAST — and a quiet arena is not written at all. The תקיפות
     heading appears only when something sits above it; the quiet line
     stays in the data but never on screen. */
  function arenaHtml(day, front) {
    const arena =
      day.arenas[front.key] || { text_he: "", devel: [], extras: [] };
    const events = eventsOf(day.date, front.key);
    const hasDevel = !!(arena.devel || []).length;
    const hasExtras = !!(arena.extras || []).length;
    if (front.key !== "general" && !events.length && !hasDevel && !hasExtras) {
      return "";
    }
    const count = countHe(events.length);
    const lead = front.key === "general" && arena.text_he
      ? '<p class="arena-text">' + esc(arena.text_he) + "</p>" : "";
    const attacks = events.length
      ? (hasDevel || hasExtras
          ? '<h4 class="cat-label">תקיפות</h4>' : "") +
        '<p class="arena-text">' + esc(arena.text_he) + "</p>" +
        '<ol class="list arena-events"></ol>'
      : "";
    return '<section class="arena" data-front="' + esc(front.key) + '">' +
      '<h3 class="arena-h">' + badgeHtml(front) +
      (count ? '<span class="arena-count">' + count + "</span>" : "") +
      "</h3>" +
      lead + develHtml(arena) + extrasHtml(arena) + attacks +
      "</section>";
  }

  /* A week's arena: same order, no extras and no cards (a heavy week is
     30+ of them); the per-day detail is one switch away. */
  function arenaWeekHtml(week, front, range) {
    const arena = week.arenas[front.key] || { text_he: "", devel: [] };
    const events = weekEventsOf(range.from, range.to, front.key);
    const hasDevel = !!(arena.devel || []).length;
    if (front.key !== "general" && !events.length && !hasDevel) return "";
    const count = countHe(events.length);
    const lead = front.key === "general" && arena.text_he
      ? '<p class="arena-text">' + esc(arena.text_he) + "</p>" : "";
    const attacks = events.length
      ? (hasDevel ? '<h4 class="cat-label">תקיפות</h4>' : "") +
        '<p class="arena-text">' + esc(arena.text_he) + "</p>"
      : "";
    return '<section class="arena" data-front="' + esc(front.key) + '">' +
      '<h3 class="arena-h">' + badgeHtml(front) +
      (count ? '<span class="arena-count">' + count + "</span>" : "") +
      "</h3>" +
      lead + develHtml(arena) + attacks +
      "</section>";
  }

  /* The same card the board renders, opened and closed LOCALLY. Never
     setActive/MapView.select from here — the map is hidden on this view and
     app.js's selection is board state. */
  function wireCard(li) {
    li.tabIndex = 0;
    li.setAttribute("aria-expanded", "false");
    li.addEventListener("click", (event) => {
      if (event.target.closest("a, summary, details")) return;
      const open = li.getAttribute("aria-expanded") === "true";
      const detail = li.querySelector(".item-detail");
      if (detail) detail.hidden = open;
      li.setAttribute("aria-expanded", open ? "false" : "true");
      li.classList.toggle("active", !open);
    });
    li.addEventListener("keydown", (event) => {
      if (event.key !== "Enter" && event.key !== " ") return;
      event.preventDefault();
      li.click();
    });
  }

  function render() {
    if (mode === "week" && !(BRIEF.weeks || []).length) mode = "day";
    if (mode === "week") renderWeek(); else renderDay();
    wireSwitch();
  }

  function renderDay() {
    const days = BRIEF.days;
    const day = days[dayIndex];
    const fronts = FRONTS.map((f) => ({ key: f.key, he: f.he, color: true }));
    /* The cross-arena residue, only when Step S actually wrote one — an empty
       bucket that exists to be empty says nothing. */
    const general = day.arenas.general;
    if (general && (general.text_he || (general.devel || []).length ||
                    (general.extras || []).length)) {
      fronts.push({ key: "general", he: "הזירה הבין־לאומית", color: false });
    }
    /* A quiet arena is skipped, so a fully quiet day would render nothing —
       and silence would read as an error, not a quiet day. Say it once. */
    const sections = fronts.map((f) => arenaHtml(day, f)).join("") ||
      '<p class="all-quiet">לא נרשמו תקיפות או התפתחויות בולטות ביום זה.</p>';

    pane.innerHTML = switchHtml() +
      '<div class="day-head">' +
      '<h2 class="day-title">' + esc(weekdayHe(day.date)) + " · " +
      fmtDate(day.date) + "</h2>" +
      '<div class="day-picker">' +
      '<button type="button" class="day-btn" id="day-prev"' +
      (dayIndex >= days.length - 1 ? " disabled" : "") + ">היום הקודם</button>" +
      '<select id="day-select" dir="ltr" aria-label="בחירת יום"></select>' +
      '<button type="button" class="day-btn" id="day-next"' +
      (dayIndex <= 0 ? " disabled" : "") + ">היום הבא</button>" +
      "</div></div>" +
      (day.checked_web === false
        ? '<p class="day-note">ליום זה לא נבדקו מקורות מעבר לערוצים שהלוח עוקב אחריהם.</p>'
        : "") +
      sections;

    /* The day list, newest first, plain digit dates — an <option> cannot hold
       the <bdi> wrapper, so the select itself is dir="ltr". */
    const select = pane.querySelector("#day-select");
    days.forEach((d, i) => {
      const [y, m, dd] = d.date.split("-");
      const option = document.createElement("option");
      option.value = String(i);
      option.textContent = Number(dd) + "." + Number(m) + "." + y;
      option.selected = i === dayIndex;
      select.appendChild(option);
    });
    select.addEventListener("change", () => {
      dayIndex = Number(select.value);
      render();
      window.scrollTo(0, 0);
    });
    pane.querySelector("#day-prev").addEventListener("click", () => {
      if (dayIndex < days.length - 1) { dayIndex += 1; render(); window.scrollTo(0, 0); }
    });
    pane.querySelector("#day-next").addEventListener("click", () => {
      if (dayIndex > 0) { dayIndex -= 1; render(); window.scrollTo(0, 0); }
    });

    /* Fill each arena's card list from the board's own renderer. */
    pane.querySelectorAll(".arena").forEach((section) => {
      const list = section.querySelector(".arena-events");
      if (!list) return;
      eventsOf(day.date, section.dataset.front).forEach((rec) => {
        const li = document.createElement("li");
        li.className = "item";
        li.innerHTML = itemHtml(rec);
        wireCard(li);
        list.appendChild(li);
      });
    });
  }

  function renderWeek() {
    const weeks = BRIEF.weeks;
    const week = weeks[weekIndex];
    const range = weekRange(week);
    const fronts = FRONTS.map((f) => ({ key: f.key, he: f.he, color: true }));
    const general = week.arenas.general;
    if (general && (general.text_he || (general.devel || []).length)) {
      fronts.push({ key: "general", he: "הזירה הבין־לאומית", color: false });
    }
    const sections = fronts.map((f) => arenaWeekHtml(week, f, range)).join("")
      || '<p class="all-quiet">לא נרשמו תקיפות או התפתחויות בולטות בשבוע זה.</p>';

    pane.innerHTML = switchHtml() +
      '<div class="day-head">' +
      '<h2 class="day-title">' + fmtDate(range.from) + " – " +
      fmtDate(range.to) + "</h2>" +
      '<div class="day-picker">' +
      '<button type="button" class="day-btn" id="week-prev"' +
      (weekIndex >= weeks.length - 1 ? " disabled" : "") +
      ">השבוע הקודם</button>" +
      '<select id="week-select" dir="ltr" aria-label="בחירת שבוע"></select>' +
      '<button type="button" class="day-btn" id="week-next"' +
      (weekIndex <= 0 ? " disabled" : "") + ">השבוע הבא</button>" +
      "</div></div>" +
      (week.checked_web === false
        ? '<p class="day-note">לשבוע זה לא נבדקו מקורות מעבר לערוצים שהלוח עוקב אחריהם.</p>'
        : "") +
      sections;

    /* Week list, newest first — plain digit ranges, dir="ltr" as the day
       select (an <option> cannot hold the <bdi> wrapper). */
    const select = pane.querySelector("#week-select");
    const short = (iso) => {
      const [, m, d] = iso.split("-");
      return Number(d) + "." + Number(m);
    };
    weeks.forEach((w, i) => {
      const r = weekRange(w);
      const option = document.createElement("option");
      option.value = String(i);
      option.textContent =
        short(r.from) + " - " + short(r.to) + "." + r.to.slice(0, 4);
      option.selected = i === weekIndex;
      select.appendChild(option);
    });
    select.addEventListener("change", () => {
      weekIndex = Number(select.value);
      render();
      window.scrollTo(0, 0);
    });
    pane.querySelector("#week-prev").addEventListener("click", () => {
      if (weekIndex < weeks.length - 1) {
        weekIndex += 1; render(); window.scrollTo(0, 0);
      }
    });
    pane.querySelector("#week-next").addEventListener("click", () => {
      if (weekIndex > 0) { weekIndex -= 1; render(); window.scrollTo(0, 0); }
    });
  }

  (function init() {
    if (typeof BRIEF === "undefined" || !BRIEF.days || !BRIEF.days.length) {
      pane.innerHTML = '<div class="empty"><p>' +
        "הסיכום היומי עדיין לא נוצר. הוא ייבנה בריצת העדכון הבאה." + "</p></div>";
      return;
    }
    render();
    if (window.Tabs) {
      /* Arriving mid-scroll from the board leaves the reader mid-document. */
      Tabs.register("daily", { show: function () { window.scrollTo(0, 0); } });
    }
  })();
})();
