/* The dossier view (the מתקפת פתע tab) — one dated document, read top to
   bottom: header, the Top 5, the maps, background, the strategic importance,
   the sources, and the day it was written. The background is the
   only DATED part, so it is the only one carrying a day picker and the only one
   that answers it.

   Data arrives via dossier_data.js (const DOSSIER, generated by
   scripts\dossier_build.py; the contract is DOSSIER.md). Two sibling globals
   do the drawing and the deck, and both are OPTIONAL at runtime:
     window.DossierMap.draw(canvas, mapId, theme, cssWidth, variant) — paints a map
     window.DossierMap.variantsOf(mapId) — ["plain", ...] the frame's pictures
     window.DossierMap.ready(theme) — Promise: the theme's relief images landed
     window.DossierDeck.build()   — Promise of { blob, fileName, mime }
   When either is missing the page says so in Hebrew, in place, and nothing
   else breaks. The maps section shows ONE BLOCK PER (map, variant), in the
   deck's own order, so what he scrolls and what he presents never differ.

   Reads app.js globals (esc, ltr, fmtDate) at call time — loaded after it.
   Never touches setActive or MapView: those are board state and the board is
   hidden while this view is on. No ES modules (file://). */
"use strict";

(function () {
  const pane = document.getElementById("dossier-pane");
  if (!pane) return;

  /* The board's own corroboration words (app.js CORROB), so a verdict here and
     a verdict on a card read the same. `claim` is one side's statement quoted
     as such: it takes the no-verdict tokens and its own word. */
  const VERDICT = {
    confirmed: { he: "מאומת", tok: "confirmed" },
    partial:   { he: "אימות חלקי", tok: "partial" },
    none:      { he: "ללא אימות עצמאי", tok: "none" },
    claim:     { he: "טענה", tok: "none" },
  };
  /* The HTML legend under each map — the same fills the board's legend names
     (index.html #lg-territory), plus the gains layer in the ground-war violet.
     Hebrew only: nothing under a map is English. */
  const LEGEND = [
    { cls: "sw fill", style: "--sw-fill: var(--geo-fill-houthi)", he: "שטח בשליטת החות'ים" },
    { cls: "sw fill", style: "--sw-fill: var(--geo-fill-gov)", he: "שטח בשליטת הכוחות הלגיטימיים" },
    { cls: "sw fill dash hatch mark", style: "--sw-fill: var(--geo-fill-contested)", he: "שטח לחימה פעיל" },
    { cls: "sw fill gain", style: "", he: "נכבש בידי החות'ים (מאומת + משוער)" },
    { cls: "sw line dash", style: "--sw-c: var(--geo-control-line); --sw-w: 2px", he: "קו חזית משוער" },
  ];
  const MISSING_MAP = "המפה אינה זמינה";
  const MISSING_DECK = "ההורדה אינה זמינה";
  const BUSY = "מכין את המצגת…";
  const FAILED = "ההורדה נכשלה.";
  const READY = "שמור את המצגת";
  const READY_HINT = "המצגת מוכנה — הקישו לשמירה.";
  const NO_SAVE = "לא ניתן לשמור כאן. פתחו את הדף בספארי או בכרום ונסו שוב.";

  let sourceById = new Map();

  /* ---- fragments --------------------------------------------------------- */

  /* An item's citations: title as the link, publisher after it. Hebrew agrees
     with the count — one source, several sources. */
  function srcHtml(ids) {
    const list = (ids || []).map((id) => sourceById.get(id)).filter(Boolean);
    if (!list.length) return "";
    const label = list.length === 1 ? "מקור" : "מקורות";
    return '<p class="ds-src">' + label + ": " + list.map((s) =>
      '<a href="' + esc(s.url) + '" target="_blank" rel="noopener">' +
      esc(s.title) + "</a>" +
      (s.publisher ? ' <span class="pub">— ' + esc(s.publisher) + "</span>" : "")
    ).join(" · ") + "</p>";
  }

  function verdictHtml(key) {
    const v = VERDICT[key];
    if (!v) return "";
    return '<span class="badge" style="--chip-c: var(--v-' + v.tok +
      "); --chip-t: var(--v-" + v.tok + '-tint)">' + esc(v.he) + "</span>";
  }

  function headHtml() {
    return '<header class="ds-head">' +
      '<h1 class="ds-title">' + esc(DOSSIER.title_he) + "</h1>" +
      (DOSSIER.subtitle_he
        ? '<p class="ds-sub">' + esc(DOSSIER.subtitle_he) + "</p>" : "") +
      '<p class="ds-asof">נכון ל-' + fmtDate(DOSSIER.as_of) + "</p>" +
      '<div class="ds-actions">' +
      '<button type="button" class="ds-btn" id="ds-deck">הורדת מצגת</button>' +
      "</div>" +
      '<p class="ds-status" id="ds-status" aria-live="polite"></p>' +
      "</header>";
  }

  function sectionOpen(section) {
    return '<section class="ds-section" data-section="' + esc(section.id) + '">' +
      '<h2 class="ds-h2">' + esc(section.heading_he) + "</h2>" +
      (section.intro_he ? '<p class="ds-intro">' + esc(section.intro_he) + "</p>" : "");
  }

  /* Top 5: Ziv's own slide format (2026-09-11) — the headline, a bar, and ONE
     short paragraph, on one line. Never split into parts; the sources ride
     under it like every other item. */
  function top5Html(top) {
    const rows = (top.items || []).map((it) =>
      '<div class="ds-item">' +
      '<p class="ds-text ds-top"><strong>' + esc(it.title_he) + "</strong>" +
      '<span class="bar" aria-hidden="true"> | </span>' + esc(it.text_he) + "</p>" +
      srcHtml(it.src) + "</div>").join("");
    return '<section class="ds-section" data-section="top5">' +
      '<h2 class="ds-h2">' + esc(top.heading_he) + "</h2>" +
      (rows ? '<div class="ds-card">' + rows + "</div>" : "") + "</section>";
  }

  /* Background: one dated row per development, the verdict and the sources on
     a meta line under the text. */
  function bgRowsHtml(items) {
    return items.map((it) =>
      '<div class="ds-item ds-row" data-date="' + esc(it.date) + '">' +
      '<div class="ds-date">' + fmtDate(it.date) + "</div>" +
      '<p class="ds-text">' + esc(it.text_he) + "</p>" +
      '<div class="ds-meta">' + verdictHtml(it.verdict) + srcHtml(it.src) + "</div>" +
      "</div>").join("");
  }

  /* The day picker — Ziv, 2026-09-12: he wanted to read one day on its own.
     The background is the only DATED thing here, so the chips sit in ITS
     header, under the heading and above its rows, and nothing else on the page
     answers them: the Top 5, the maps and the two analysis sections carry no
     dates and never move. One day at a time (a picker, not a multi-select),
     all-days is the resting state, and the deck is untouched — a presentation
     is the whole document.
     The chips ARE the board's chips: .chip / .chips / .chips-label from
     style.css with the same --chip-c / --chip-t tokens, only lifted to this
     page's reading scale, the way .badge is. Each prints its own
     count, so the shape of the days is readable before anything is pressed. */
  const ALL_DAYS = "";
  let dayPick = ALL_DAYS;
  let bgItems = [];

  function dayChipHtml(day, he, count) {
    const on = day === dayPick;
    return '<button type="button" class="chip' + (on ? " on" : "") +
      '" data-day="' + esc(day) + '" aria-pressed="' + (on ? "true" : "false") +
      '" style="--chip-c: var(--accent-text); --chip-t: var(--accent-tint)">' +
      "<span>" + he + '</span><span class="n">' + count + "</span></button>";
  }

  /* One chip per day that actually has items, in date order, plus the all-days
     chip. A section that holds a single day is not a choice — no row is drawn. */
  function daysHtml(items) {
    const counts = new Map();
    items.forEach((it) => counts.set(it.date, (counts.get(it.date) || 0) + 1));
    if (counts.size < 2) return "";
    return '<div class="ds-days chips" role="group" aria-labelledby="ds-days-lbl">' +
      '<span class="chips-label" id="ds-days-lbl">לפי יום</span>' +
      dayChipHtml(ALL_DAYS, "כל הימים", items.length) +
      Array.from(counts.keys()).sort().map((d) =>
        dayChipHtml(d, fmtDate(d), counts.get(d))).join("") +
      "</div>";
  }

  function backgroundHtml(section) {
    bgItems = section.items || [];
    return sectionOpen(section) + daysHtml(bgItems) +
      (bgItems.length
        ? '<div class="ds-card" id="ds-bg-card">' + bgRowsHtml(bgItems) + "</div>" : "") +
      "</section>";
  }

  /* The rows are REBUILT rather than hidden: `.ds-item:last-child` drops the
     row rule, and a hidden last row would leave that hairline under the card's
     last visible one. The counts are the day's own totals and never move with
     the pick — the same rule the band's chips follow. */
  function applyDay() {
    const card = pane.querySelector("#ds-bg-card");
    if (card) {
      card.innerHTML = bgRowsHtml(
        dayPick ? bgItems.filter((it) => it.date === dayPick) : bgItems);
    }
    pane.querySelectorAll(".ds-days .chip").forEach((btn) => {
      const on = (btn.dataset.day || ALL_DAYS) === dayPick;
      btn.classList.toggle("on", on);
      btn.setAttribute("aria-pressed", on ? "true" : "false");
    });
  }

  function wireDays() {
    pane.querySelectorAll(".ds-days .chip").forEach((btn) => {
      btn.addEventListener("click", () => {
        const day = btn.dataset.day || ALL_DAYS;
        /* Pressing the day that is already on releases it, so the chip that
           narrowed the section is also the one that widens it again. */
        dayPick = day === dayPick ? ALL_DAYS : day;
        applyDay();
      });
    });
  }

  /* The strategic importance: a titled item — a heading and its paragraph,
     with the sources under it like every other item. */
  function titledHtml(section) {
    const rows = (section.items || []).map((it) =>
      '<div class="ds-item">' +
      '<h3 class="ds-h3"><span>' + esc(it.title_he) + "</span></h3>" +
      '<p class="ds-text">' + esc(it.text_he) + "</p>" +
      srcHtml(it.src) + "</div>").join("");
    return sectionOpen(section) +
      (rows ? '<div class="ds-card">' + rows + "</div>" : "") + "</section>";
  }

  function legendHtml() {
    return '<div class="ds-legend" aria-label="מקרא המפה">' +
      LEGEND.map((r) =>
      '<span class="ds-lg-row"><span class="' + r.cls + '"' +
      (r.style ? ' style="' + r.style + '"' : "") + "></span>" + esc(r.he) + "</span>"
    ).join("") + "</div>";
  }

  /* The frame's own shape (3:2 for the close-up, 16:9 for the overview), so
     the box has the canvas's shape before anything is drawn in it. */
  function aspectOf(id) {
    const a = window.DossierMap && DossierMap.aspect ? DossierMap.aspect(id) : 16 / 9;
    return a.toFixed(4);
  }

  /* The pictures the painter can draw for a frame, plain first — the deck's own
     list, so the page and the file carry the same blocks. Without the call (an
     older painter) a map is its one plain picture. */
  function variantsOf(id) {
    if (window.DossierMap && typeof DossierMap.variantsOf === "function") {
      try {
        const v = DossierMap.variantsOf(id);
        if (Array.isArray(v) && v.length) return v;
      } catch (e) { /* fall through to the plain picture */ }
    }
    return ["plain"];
  }

  /* A block's heading: the map's own title when it has one, else the caption's
     first clause. The cut is at a full stop or a SPACED dash — never a bare
     hyphen, which in Hebrew joins a prefix to a number ("נכון ל-12"). */
  function clauseOf(text) {
    const t = String(text || "").trim();
    const m = /[.。]|\s[—–-]\s/.exec(t);
    return (m ? t.slice(0, m.index) : t).replace(/[,،]\s*$/, "").trim();
  }
  function blockHeading(m, variant) {
    if (variant) return clauseOf(variant.caption_he) || blockHeading(m, null);
    return String(m.title_he || "").trim() || clauseOf(m.caption_he);
  }

  /* When the heading was CUT OUT of the caption, the caption prints what is LEFT.
     Design law: a row never repeats the name of the group it sits in - and a
     one-clause caption with no title beside it would otherwise print twice, once
     as the heading and once under the map. */
  function captionAfter(text, heading) {
    const t = String(text || "").trim();
    if (!heading || t.indexOf(heading) !== 0) return t;
    return t.slice(heading.length).replace(/^[\s.,،。—–-]+/, "").trim();
  }

  function mapBlockHtml(m, key, variant) {
    const heading = blockHeading(m, variant);
    const raw = variant ? (variant.caption_he || "") : (m.caption_he || "");
    const cut = variant ? true : !String(m.title_he || "").trim();
    const caption = cut ? captionAfter(raw, heading) : raw;
    return '<section class="ds-map" data-map="' + esc(m.id) + '" data-variant="' + esc(key) + '">' +
      (heading ? '<h3 class="ds-map-h">' + esc(heading) + "</h3>" : "") +
      '<div class="ds-map-wide"><div class="ds-map-box" style="--ar: ' + aspectOf(m.id) + '">' +
      '<canvas class="ds-canvas" data-map-id="' + esc(m.id) + '" data-variant="' + esc(key) +
      '" role="img" aria-label="' + esc(heading) + '"></canvas>' +
      (window.DossierMap ? "" : '<p class="ds-map-missing">' + MISSING_MAP + "</p>") +
      "</div></div>" +
      (caption ? '<p class="ds-caption">' + esc(caption) + "</p>" : "") +
      legendHtml() +
      "</section>";
  }

  /* One block per (map, variant), every variant of a map together, in the order
     the deck lays its slides. The plain picture reads the map's own caption; a
     variant reads its own. */
  function mapsHtml() {
    return (DOSSIER.maps || []).map((m) => variantsOf(m.id).map((key) => {
      const v = key !== "plain" && m.variants && m.variants[key] ? m.variants[key] : null;
      return mapBlockHtml(m, key, v);
    }).join("")).join("");
  }

  /* Derived from sources[] — never authored twice (DOSSIER.md). */
  function sourcesHtml() {
    const list = DOSSIER.sources || [];
    if (!list.length) return "";
    return '<section class="ds-section" data-section="sources">' +
      '<h2 class="ds-h2">מקורות</h2><ol class="ds-sources">' +
      list.map((s) =>
        '<li><a href="' + esc(s.url) + '" target="_blank" rel="noopener">' +
        esc(s.title) + "</a>" +
        (s.publisher ? ' <span class="pub">— ' + esc(s.publisher) + "</span>" : "") +
        (s.date ? ' <span class="when">· ' + fmtDate(s.date) + "</span>" : "") +
        "</li>").join("") +
      "</ol></section>";
  }

  /* ---- render ------------------------------------------------------------ */

  function render() {
    sourceById = new Map((DOSSIER.sources || []).map((s) => [s.id, s]));
    const byId = {};
    (DOSSIER.sections || []).forEach((s) => { byId[s.id] = s; });
    const parts = [headHtml()];
    if (DOSSIER.top5) parts.push(top5Html(DOSSIER.top5));
    /* The maps come straight after the Top 5, ahead of the dated background —
       Ziv, 2026-09-12: below the background they cost a long scroll to reach. */
    parts.push(mapsHtml());
    if (byId.background) parts.push(backgroundHtml(byId.background));
    if (byId.importance) parts.push(titledHtml(byId.importance));
    parts.push(sourcesHtml());
    parts.push('<p class="ds-written">נכתב: ' + fmtDate(DOSSIER.written) + "</p>");
    pane.innerHTML = parts.join("");
    wireButtons();
    if (window.DossierPng) DossierPng.mount(pane);
    wireDays();
    repaintWhenReady();
  }

  /* ---- the maps ---------------------------------------------------------- */

  /* Measured from the BOX, not the canvas: the painter writes the canvas's
     CSS size inline, so after a resize the canvas still reports the old
     width while the box already has the new one. Skipped while hidden — a
     display:none pane measures zero, and a zero-width map is a blank one. */
  function drawMaps() {
    if (!window.DossierMap || !document.body.classList.contains("view-dossier")) return;
    pane.querySelectorAll(".ds-canvas").forEach((canvas) => {
      const width = canvas.parentElement.clientWidth;
      if (width <= 0) return;
      DossierMap.draw(canvas, canvas.dataset.mapId, "dark", width, canvas.dataset.variant);
    });
  }

  /* A relief map painted before its picture landed is a plain map: once the
     painter says the theme's images are in, everything is painted again. An
     older painter without the call has nothing to wait for. */
  function repaintWhenReady() {
    if (!window.DossierMap || typeof DossierMap.ready !== "function") return;
    Promise.resolve().then(() => DossierMap.ready("dark")).then(drawMaps, () => {});
  }

  let resizeTimer = 0;
  window.addEventListener("resize", () => {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(drawMaps, 150);
  });

  /* ---- the deck ---------------------------------------------------------- */

  function setStatus(text) {
    const el = pane.querySelector("#ds-status");
    if (el) el.textContent = text || "";
  }

  /* A rejection carries a Hebrew message the reader can act on; anything else
     (a TypeError, a network failure's English) is not for him. */
  function rejectionText(err) {
    const text = err == null ? "" : (typeof err === "string" ? err : String(err.message || err));
    return /[֐-׿]/.test(text) ? text : FAILED;
  }

  /* iPhone does not DOWNLOAD a blob: URL from an <a download> - WebKit navigates
     to it instead, and a chat app's in-app browser cannot render a .pptx. That is
     the "WebKitBlobResource - 1" Ziv photographed on 2026-09-12, on a deck that
     saves correctly on the desktop. The phone's own answer is the share sheet,
     which hands the file to Files, to PowerPoint or to anything else he has.
     `navigator.share` needs a LIVE tap and the build takes a second or two, which
     spends the tap he already gave - so on a phone the first tap BUILDS and the
     second SHARES, and the button says which it is waiting for.
     `?deck=share` forces the same path on a desktop: the branch a phone takes is
     otherwise unreachable from here, and an untested branch is the one that
     breaks in his hand. */
  const IOS = /iP(hone|od|ad)/.test(navigator.userAgent) ||
    (navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1) ||
    /[?&]deck=share(&|$)/.test(location.search);

  function shareable(file) {
    return !!(navigator.share && navigator.canShare &&
              navigator.canShare({ files: [file] }));
  }

  /* The anchor and its URL both outlive the click: WebKit aborts a save whose
     anchor or blob was taken away in the same tick. */
  function saveByLink(made) {
    const url = URL.createObjectURL(made.blob);
    const a = document.createElement("a");
    a.href = url; a.download = made.fileName; a.style.display = "none";
    document.body.appendChild(a);
    a.click();
    setTimeout(() => a.remove(), 2000);
    setTimeout(() => URL.revokeObjectURL(url), 60000);
  }
  /* The per-map PNG buttons save through this same helper (dossier_png.js): one
     save path on the page, so a WebKit fix here reaches every download. */
  window.DossierSave = saveByLink;

  /* The built file, waiting for the tap that will share it. */
  let pending = null;
  function clearPending() {
    if (pending) pending.btn.textContent = pending.label;
    pending = null;
  }

  function wireButtons() {
    const buttons = Array.from(pane.querySelectorAll(".ds-btn"));
    if (!window.DossierDeck) {
      buttons.forEach((b) => { b.disabled = true; });
      setStatus(MISSING_DECK);
      return;
    }
    buttons.forEach((btn) => {
      const label = btn.textContent;
      btn.addEventListener("click", () => {
        if (pending && pending.btn === btn) {
          const file = pending.file;
          clearPending();
          setStatus("");
          navigator.share({ files: [file], title: file.name }).catch((err) => {
            /* He closed the sheet himself - that is not a failure to report. */
            if (err && err.name === "AbortError") return;
            setStatus(NO_SAVE);
          });
          return;
        }
        clearPending();
        /* Held while it runs: a second tap mid-build would fetch the library
           twice and race the first. One button since 2026-09-15; the loop still
           holds every .ds-btn, so a control added beside it is held too. */
        buttons.forEach((b) => { b.disabled = true; });
        btn.textContent = BUSY;
        setStatus("");
        const restore = () => {
          btn.textContent = label;
          buttons.forEach((b) => { b.disabled = false; });
        };
        Promise.resolve()
          .then(() => DossierDeck.build("light"))
          .then((made) => {
            buttons.forEach((b) => { b.disabled = false; });
            /* An old WebKit with no File constructor still gets the link path
               rather than a thrown error inside the tap. */
            let file = null;
            try {
              file = new File([made.blob], made.fileName, { type: made.mime });
            } catch (e) { file = null; }
            if (IOS && file && shareable(file)) {
              pending = { btn: btn, label: label, file: file };
              btn.textContent = READY;
              setStatus(READY_HINT);
              return;
            }
            restore();
            /* On a phone with no share sheet the link cannot work either - say
               so, rather than letting the tap do nothing at all. */
            if (IOS) { setStatus(NO_SAVE); return; }
            saveByLink(made);
          }, (err) => { restore(); setStatus(rejectionText(err)); });
      });
    });
  }

  /* ---- init -------------------------------------------------------------- */

  (function init() {
    if (typeof DOSSIER === "undefined") {
      pane.innerHTML = '<div class="empty"><p>' +
        "הדוח עדיין לא נוצר. הוא ייבנה בריצת העדכון הבאה." + "</p></div>";
    } else {
      render();
    }
    if (window.Tabs) {
      /* show() runs with the pane already visible and measurable (tabs.js),
         which is the one moment a canvas can be sized from its box. */
      Tabs.register("dossier", {
        show: function () { window.scrollTo(0, 0); drawMaps(); repaintWhenReady(); },
      });
    }
  })();
})();
