/* The dossier view (the רקע ומשמעויות tab) — one dated document, read top to
   bottom: header, the Top 5, background, the two maps, the strategic importance, the
   meanings, the sources, and the day it was written.

   Data arrives via dossier_data.js (const DOSSIER, generated by
   scripts\dossier_build.py; the contract is DOSSIER.md). Two sibling globals
   do the drawing and the deck, and both are OPTIONAL at runtime:
     window.DossierMap.draw(canvas, mapId, theme, cssWidth)  — paints a map
     window.DossierDeck.download(theme)                      — Promise, builds the .pptx
   When either is missing the page says so in Hebrew, in place, and nothing
   else breaks.

   Reads app.js globals (esc, ltr, fmtDate) at call time — loaded after it.
   Never touches setActive or MapView: those are board state and the board is
   hidden while this view is on. No ES modules (file://). */
"use strict";

(function () {
  const pane = document.getElementById("dossier-pane");
  if (!pane) return;

  /* The board's own corroboration words (app.js CORROB), so a verdict here and
     a verdict on a card read the same. `claim` is one side's statement quoted
     as such: it takes the no-verdict tokens and its own word. */
  const VERDICT = {
    confirmed: { he: "מאומת", tok: "confirmed" },
    partial:   { he: "אימות חלקי", tok: "partial" },
    none:      { he: "ללא אימות עצמאי", tok: "none" },
    claim:     { he: "טענה", tok: "none" },
  };
  /* For whom a meaning is written. An unknown kind renders untagged rather
     than mislabelled. */
  const KIND_HE = {
    shipping: "לספנות",
    saudi: "לסעודיה",
    israel: "לישראל",
    yemen: "לממשלת תימן ולקואליציה",
    iran: "לאיראן ולציר",
    watch: "מה לעקוב",
  };
  /* The HTML legend under each map — the same fills the board's legend names
     (index.html #lg-territory), plus the gains layer in the ground-war violet.
     Hebrew only: nothing under a map is English. */
  const LEGEND = [
    { cls: "sw fill", style: "--sw-fill: var(--geo-fill-houthi)", he: "שטח בשליטת החות'ים" },
    { cls: "sw fill", style: "--sw-fill: var(--geo-fill-gov)", he: "שטח בשליטת הכוחות הלגיטימיים" },
    { cls: "sw fill dash hatch", style: "--sw-fill: var(--geo-fill-contested)", he: "שטח לחימה פעיל" },
    { cls: "sw fill gain", style: "", he: "נכבש בידי החות'ים (מאומת + משוער)" },
    { cls: "sw line dash", style: "--sw-c: var(--geo-control-line); --sw-w: 2px", he: "קו חזית משוער" },
  ];
  const MISSING_MAP = "המפה אינה זמינה";
  const MISSING_DECK = "ההורדה אינה זמינה";
  const BUSY = "מכין את המצגת…";
  const FAILED = "ההורדה נכשלה.";

  let sourceById = new Map();

  /* ---- fragments --------------------------------------------------------- */

  /* An item's citations: title as the link, publisher after it. Hebrew agrees
     with the count — one source, several sources. */
  function srcHtml(ids) {
    const list = (ids || []).map((id) => sourceById.get(id)).filter(Boolean);
    if (!list.length) return "";
    const label = list.length === 1 ? "מקור" : "מקורות";
    return '<p class="ds-src">' + label + ": " + list.map((s) =>
      '<a href="' + esc(s.url) + '" target="_blank" rel="noopener">' +
      esc(s.title) + "</a>" +
      (s.publisher ? ' <span class="pub">— ' + esc(s.publisher) + "</span>" : "")
    ).join(" · ") + "</p>";
  }

  function verdictHtml(key) {
    const v = VERDICT[key];
    if (!v) return "";
    return '<span class="badge" style="--chip-c: var(--v-' + v.tok +
      "); --chip-t: var(--v-" + v.tok + '-tint)">' + esc(v.he) + "</span>";
  }

  function headHtml() {
    return '<header class="ds-head">' +
      '<h1 class="ds-title">' + esc(DOSSIER.title_he) + "</h1>" +
      (DOSSIER.subtitle_he
        ? '<p class="ds-sub">' + esc(DOSSIER.subtitle_he) + "</p>" : "") +
      '<p class="ds-asof">נכון ל-' + fmtDate(DOSSIER.as_of) + "</p>" +
      '<div class="ds-actions">' +
      '<button type="button" class="ds-btn" data-theme="dark">הורדת מצגת — כהה</button>' +
      '<button type="button" class="ds-btn" data-theme="light">הורדת מצגת — בהירה</button>' +
      "</div>" +
      '<p class="ds-status" id="ds-status" aria-live="polite"></p>' +
      "</header>";
  }

  function sectionOpen(section) {
    return '<section class="ds-section" data-section="' + esc(section.id) + '">' +
      '<h2 class="ds-h2">' + esc(section.heading_he) + "</h2>" +
      (section.intro_he ? '<p class="ds-intro">' + esc(section.intro_he) + "</p>" : "");
  }

  /* Top 5: Ziv's own slide format (2026-09-11) — the headline, a bar, and ONE
     short paragraph, on one line. Never split into parts; the sources ride
     under it like every other item. */
  function top5Html(top) {
    const rows = (top.items || []).map((it) =>
      '<div class="ds-item">' +
      '<p class="ds-text ds-top"><strong>' + esc(it.title_he) + "</strong>" +
      '<span class="bar" aria-hidden="true"> | </span>' + esc(it.text_he) + "</p>" +
      srcHtml(it.src) + "</div>").join("");
    return '<section class="ds-section" data-section="top5">' +
      '<h2 class="ds-h2">' + esc(top.heading_he) + "</h2>" +
      (rows ? '<div class="ds-card">' + rows + "</div>" : "") + "</section>";
  }

  /* Background: one dated row per development, the verdict and the sources on
     a meta line under the text. */
  function backgroundHtml(section) {
    const rows = (section.items || []).map((it) =>
      '<div class="ds-item ds-row">' +
      '<div class="ds-date">' + fmtDate(it.date) + "</div>" +
      '<p class="ds-text">' + esc(it.text_he) + "</p>" +
      '<div class="ds-meta">' + verdictHtml(it.verdict) + srcHtml(it.src) + "</div>" +
      "</div>").join("");
    return sectionOpen(section) +
      (rows ? '<div class="ds-card">' + rows + "</div>" : "") + "</section>";
  }

  /* Importance and meanings: a titled item. The meaning's kind rides before
     its title as a quiet tag — unless the title already IS that word, in
     which case printing it twice says nothing. */
  function titledHtml(section, withKind) {
    const rows = (section.items || []).map((it) => {
      const kind = withKind ? KIND_HE[it.kind] : "";
      const tag = kind && kind !== it.title_he
        ? '<span class="tag">' + esc(kind) + "</span>" : "";
      return '<div class="ds-item">' +
        '<h3 class="ds-h3">' + tag + "<span>" + esc(it.title_he) + "</span></h3>" +
        '<p class="ds-text">' + esc(it.text_he) + "</p>" +
        srcHtml(it.src) + "</div>";
    }).join("");
    return sectionOpen(section) +
      (rows ? '<div class="ds-card">' + rows + "</div>" : "") + "</section>";
  }

  function legendHtml() {
    return '<div class="ds-legend" aria-label="מקרא המפה">' + LEGEND.map((r) =>
      '<span class="ds-lg-row"><span class="' + r.cls + '"' +
      (r.style ? ' style="' + r.style + '"' : "") + "></span>" + esc(r.he) + "</span>"
    ).join("") + "</div>";
  }

  /* The frame's own shape (3:2 for the close-up, 16:9 for the overview), so
     the box has the canvas's shape before anything is drawn in it. */
  function aspectOf(id) {
    const a = window.DossierMap && DossierMap.aspect ? DossierMap.aspect(id) : 16 / 9;
    return a.toFixed(4);
  }

  function mapsHtml() {
    return (DOSSIER.maps || []).map((m) =>
      '<section class="ds-map" data-map="' + esc(m.id) + '">' +
      '<h2 class="ds-h2">' + esc(m.title_he) + "</h2>" +
      '<div class="ds-map-wide"><div class="ds-map-box" style="--ar: ' + aspectOf(m.id) + '">' +
      '<canvas class="ds-canvas" data-map-id="' + esc(m.id) + '" role="img" aria-label="' +
      esc(m.title_he) + '"></canvas>' +
      (window.DossierMap ? "" : '<p class="ds-map-missing">' + MISSING_MAP + "</p>") +
      "</div></div>" +
      (m.caption_he ? '<p class="ds-caption">' + esc(m.caption_he) + "</p>" : "") +
      legendHtml() +
      "</section>").join("");
  }

  /* Derived from sources[] — never authored twice (DOSSIER.md). */
  function sourcesHtml() {
    const list = DOSSIER.sources || [];
    if (!list.length) return "";
    return '<section class="ds-section" data-section="sources">' +
      '<h2 class="ds-h2">מקורות</h2><ol class="ds-sources">' +
      list.map((s) =>
        '<li><a href="' + esc(s.url) + '" target="_blank" rel="noopener">' +
        esc(s.title) + "</a>" +
        (s.publisher ? ' <span class="pub">— ' + esc(s.publisher) + "</span>" : "") +
        (s.date ? ' <span class="when">· ' + fmtDate(s.date) + "</span>" : "") +
        "</li>").join("") +
      "</ol></section>";
  }

  /* ---- render ------------------------------------------------------------ */

  function render() {
    sourceById = new Map((DOSSIER.sources || []).map((s) => [s.id, s]));
    const byId = {};
    (DOSSIER.sections || []).forEach((s) => { byId[s.id] = s; });
    const parts = [headHtml()];
    if (DOSSIER.top5) parts.push(top5Html(DOSSIER.top5));
    if (byId.background) parts.push(backgroundHtml(byId.background));
    parts.push(mapsHtml());
    if (byId.importance) parts.push(titledHtml(byId.importance, false));
    if (byId.meanings) parts.push(titledHtml(byId.meanings, true));
    parts.push(sourcesHtml());
    parts.push('<p class="ds-written">נכתב: ' + fmtDate(DOSSIER.written) + "</p>");
    pane.innerHTML = parts.join("");
    wireButtons();
  }

  /* ---- the maps ---------------------------------------------------------- */

  /* Measured from the BOX, not the canvas: the painter writes the canvas's
     CSS size inline, so after a resize the canvas still reports the old
     width while the box already has the new one. Skipped while hidden — a
     display:none pane measures zero, and a zero-width map is a blank one. */
  function drawMaps() {
    if (!window.DossierMap || !document.body.classList.contains("view-dossier")) return;
    pane.querySelectorAll(".ds-canvas").forEach((canvas) => {
      const width = canvas.parentElement.clientWidth;
      if (width <= 0) return;
      DossierMap.draw(canvas, canvas.dataset.mapId, "dark", width);
    });
  }

  let resizeTimer = 0;
  window.addEventListener("resize", () => {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(drawMaps, 150);
  });

  /* ---- the deck ---------------------------------------------------------- */

  function setStatus(text) {
    const el = pane.querySelector("#ds-status");
    if (el) el.textContent = text || "";
  }

  /* A rejection carries a Hebrew message the reader can act on; anything else
     (a TypeError, a network failure's English) is not for him. */
  function rejectionText(err) {
    const text = err == null ? "" : (typeof err === "string" ? err : String(err.message || err));
    return /[֐-׿]/.test(text) ? text : FAILED;
  }

  function wireButtons() {
    const buttons = Array.from(pane.querySelectorAll(".ds-btn"));
    if (!window.DossierDeck) {
      buttons.forEach((b) => { b.disabled = true; });
      setStatus(MISSING_DECK);
      return;
    }
    buttons.forEach((btn) => {
      btn.addEventListener("click", () => {
        const label = btn.textContent;
        /* Both are held while one runs: two decks building at once would
           fetch the same library twice and race each other's save. */
        buttons.forEach((b) => { b.disabled = true; });
        btn.textContent = BUSY;
        setStatus("");
        const restore = () => {
          btn.textContent = label;
          buttons.forEach((b) => { b.disabled = false; });
        };
        Promise.resolve()
          .then(() => DossierDeck.download(btn.dataset.theme))
          .then(restore, (err) => { restore(); setStatus(rejectionText(err)); });
      });
    });
  }

  /* ---- init -------------------------------------------------------------- */

  (function init() {
    if (typeof DOSSIER === "undefined") {
      pane.innerHTML = '<div class="empty"><p>' +
        "הדוח עדיין לא נוצר. הוא ייבנה בריצת העדכון הבאה." + "</p></div>";
    } else {
      render();
    }
    if (window.Tabs) {
      /* show() runs with the pane already visible and measurable (tabs.js),
         which is the one moment a canvas can be sized from its box. */
      Tabs.register("dossier", {
        show: function () { window.scrollTo(0, 0); drawMaps(); },
      });
    }
  })();
})();
